Find boost program_option when building tests
PixarAnimationStudios/USD pull request #1703
Opened 2021-12-04 21:44 UTC by charlesfleche

### Description of Change(s)

https://github.com/PixarAnimationStudios/USD/pull/1649 introduced a bug that prevent test to link when USD is built statically. This PR fixes it by finding boost program_option if either `PXR_BUILD_USD_TOOLS` or `PXR_BUILD_TESTS` are `ON`.

### Fixes Issue(s)
- #1698

2021-12-04 22:07 UTC, Sarkar44 approved these changes

2021-12-04 22:09 UTC, Sarkar44 requested changes
Suggesting change

2021-12-04 22:13 UTC, Sarkar44 requested changes
Suggesting change

2021-12-08 23:58 UTC, jilliene commented
Filed as internal issue #USD-7055

2021-12-18 07:01 UTC, merged