APPLE: IOS enablement
PixarAnimationStudios/USD pull request #2004
Opened 2022-08-22 05:19 UTC by slingthor

### Description of Change(s)

- Add a new iOS toolchain
- Modify build script to accomedate building on Apple. Most likely not merged in until cross platform module created as well
- Modifies cmake files in project to accomedate appleios building
- Work around for base primitive offset in post tessellation vertex shaders
- Depends on improvement to post tessellation triquads from intel enablement
- Takes into account iOS and macOS specific differences
- Builds several items as static libraries to skip issues with code signing and provisioning profiles for every built library in cmake
- Should not be built with Python
- Proven to work on iOS version > 14.0 or higher
- Tested not to break existing Linux and MacOS

- [X] I have submitted a signed Contributor License Agreement

2022-08-25 00:51 UTC, sunyab commented
Filed as internal issue #USD-7580

2022-09-05 10:56 UTC, jonny-apple requested changes

2022-09-05 10:56 UTC, jonny-apple commented on cmake/defaults/Packages.cmake
> +    set(OPENSUBDIV_USE_GPU (${PXR_ENABLE_GL_SUPPORT} OR APLLEIOS))
APLLEIOS incorrect spelling

2022-09-05 10:56 UTC, jonny-apple commented on pxr/imaging/glf/CMakeLists.txt
> +    pxr_library(glf
Whitespace changed, should probably keep this the same.

2022-11-29 17:12 UTC, closed without merging