APPLE: Texture and buffer writability in Metal/HGI along with settings where appropriate
PixarAnimationStudios/USD pull request #2042
Opened 2022-09-15 15:36 UTC by slingthor

### Description of Change(s)
Allows HGI to define readonly buffers and textures.
Take advantage of that in the resource binder and hdx where we manually set up resources
Sets buffers we don't index into to live in constant space, and pass them as const reference instead of as a pointer

- [X] I have submitted a signed Contributor License Agreement

2022-09-19 19:35 UTC, tallytalwar commented
Filed as internal issue #USD-7640

2022-09-20 08:02 UTC, jonny-apple requested changes

2022-09-20 08:02 UTC, jonny-apple commented on pxr/imaging/hgi/resourceBindings.h
> +    bool readOnly;
In shadersection we use `_writable` while here we use readOnly.  For consistency shouldn't they be the same?

2022-09-20 12:37 UTC, jonny-apple requested changes
Make sure that the `readOnly` flag is initialised in every instance of the `HgiBufferBindDesc` creation.  There's a few instances in `flatNormals.cpp`, `quadrangulate.cpp`, `resourceBinder.cpp`, `smoothNormals.cpp`, `subdivision.cpp`, `boundingBoxTask.cpp`,  that need to be covered.

Also the comparator in `resourceBindings.cpp` needs to include a test for the flag.

2022-09-20 13:53 UTC, slingthor commented
PR updated! Will be sharing some metrics on MacOS as well

2022-09-22 07:18 UTC, jonny-apple approved these changes

2022-09-28 19:35 UTC, merged