Adding python bindings for VtArray<SdfPathExpression> objects.
PixarAnimationStudios/USD pull request #3309
Opened 2024-09-21 01:02 UTC by marktucker

### Description of Change(s)
Adding python bindings for VtArray<SdfPathExpression> objects.

Without these additions, it is not possible to use python to get or set attributes or metadata of type Sdf.ValueTypeNames.PathExpressionArray. There is obviously no pressing need for this as there are no schemas (that I am aware of) that use this data type, but since this is a valid data type, it seemed to me that it should be possible to use it in python.

- [ X ] I have verified that all unit tests pass with the proposed changes
- [ X ] I have submitted a signed Contributor License Agreement

2024-09-23 16:57 UTC, jesschimein commented
Filed as internal issue #USD-10177

2024-09-23 16:57 UTC, jesschimein commented
/AzurePipelines run

2025-02-18 00:50 UTC, sunyab requested changes
Hey @marktucker , left some notes for you, thanks!

2025-02-18 00:50 UTC, sunyab commented on pxr/usd/sdf/testenv/testSdfPathExpressionArray.py
> +# Copyright 2024 Pixar
2024 -> 2025

2025-02-18 00:50 UTC, sunyab commented on pxr/usd/sdf/wrapArrayPathExpression.cpp
> +// Copyright 2016 Pixar
2016 -> 2025

2025-02-18 00:50 UTC, sunyab commented on pxr/usd/sdf/pathExpression.cpp
> +
We'd prefer to disallow implicit casts from std::string to SdfPathExpression. Construction of an SdfPathExpression may raise a TfError if the input string doesn't parse, so we'd prefer the user be explicit about when they want to do the conversion and be aware of the potential error.

I believe that means we can remove this and the implicit_convertible registration I'll call out below.

2025-02-18 00:50 UTC, sunyab commented on pxr/usd/sdf/wrapPathExpression.cpp
> +    implicitly_convertible<std::string, SdfPathExpression>();
See comment above. An additional reason to disallow the implicit conversion is that it can lead to surprising scene description being authored if the input string is invalid. For example:

```
>>> from pixar import Sdf
>>> l = Sdf.Layer.CreateAnonymous('.usda')
>>> p = Sdf.CreatePrimInLayer(l, '/foo')
>>> a = Sdf.AttributeSpec(p, 'a', Sdf.ValueTypeNames.PathExpression)
>>> a.default = '%#$@'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pixar.Tf.ErrorException: 
        Error in 'SdfPathExpression::SdfPathExpression' at line 69 in file pxr/usd/sdf/pathExpression.cpp : '<input>:1:1: parse error matching pxr_pegtl::pad<{anonymous}::PathExpr, pxr_pegtl::ascii::blank, pxr_pegtl::ascii::blank> -- <input>:1:1'

>>> print(l.ExportToString())
#usda 1.0

over "foo"
{
    pathExpression a = ""
}
```

2025-02-19 00:58 UTC, marktucker commented on pxr/usd/sdf/testenv/testSdfPathExpressionArray.py
> +# Copyright 2024 Pixar
To be fair, it was 2024 when I submitted this PR :)

2025-02-20 17:39 UTC, jesschimein commented
/AzurePipelines run

2025-05-01 14:56 UTC, nvmkuruc commented
Hi @sunyab and @marktucker, was this merged as 33a027070c197d68a5a52336a97261bc66c7c577?

2025-05-01 15:53 UTC, jesschimein commented
It was!  Thanks for catching that!  Closing this issue as fixed.

2025-05-01 15:53 UTC, closed without merging